### ISSUE TITLE
Ledger Values not showing up

### ISSUE THREAD

**Issue by hackingpirate1** [austintgriffith/eth.build#66]
I create an object with a different value but the ledger does not show the changes. It just shows 0 as the value.
![image](https://user-images.githubusercontent.com/57339819/125271583-8e44c280-e328-11eb-85ca-05b127c2b48f.png)

**Comment by rmbishop** [comment]
I wonder if the value is actually "10.00", but the ledger cannot show it.  Try adding a 1 digit value and see if that shows up.

**Comment by rmbishop** [comment]
The value you specific in the tx is in wei, but the value in the ledger is in eth.
If you use a value of 1000000000000000000, the ledger will show 1.00

**Comment by grahamtallen** [comment]
@hackingpirate1 Ok to close?

**Comment by jasonallen** [comment]
I also ran into this issue. The problem is that Austin's tutorials show him using Eth in the "value" field. So when I recreated his ledger intro it appeared to me like there was a bug. My best idea is to document it someway, or add an overlay-note on Austin's youtube video to warn viewers that the field changed from Eth -> Wei.
